### PR TITLE
282e 2024.09.02

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
The bouquets have been created by Enigma2 using the remote. Not by a channel editor.

**Comment by Lexzie** [comment]
> The bouquets have been created by Enigma2 using the remote. Not by a channel editor.

What's the difference?

**Comment by AbuBaniaz** [comment]
The existing bouquet  seem to be in lowercase. I didn't want to interfere with them in case they were incompatible with the source from which you get them or the bouquet editor you use.

A large number of channels on the original 28.2 bouquet file come up as N/A  until I re-scan selecting clear first. I don't know why. 
Enigma2 orders them numerically then alphabetically
Filename is slightly different.

Please also see this comment
https://github.com/picons/picons/issues/2343#issuecomment-2324345513

**Comment by AbuBaniaz** [comment]
@Lexzie 
Are you downloading these lists or scanning/creating them yourself?
Can you please check whether converting the bouquet files to upper case causes problems for your editor?
https://code2care.org/2020/notepad-plus-plus-convert-text-lowercase-uppercase/

**Comment by Lexzie** [comment]
> The existing bouquet seem to be in lowercase. I didn't want to interfere with them in case they were incompatible with the source from which you get them or the bouquet editor you use.
> 
> A large number of channels on the original 28.2 bouquet file come up as N/A until I re-scan selecting clear first. I don't know why. Enigma2 orders them numerically then alphabetically Filename is slightly different.
> 
> Please also see this comment [picons/picons#2343 (comment)](https://github.com/picons/picons/issues/2343#issuecomment-2324345513)

Yes, I was wondering too why it was in lower case. At least as far as I know is not done by my editor (Dreamset).

I am very pleased that you took the time to update it.

**Comment by AbuBaniaz** [comment]
I would be grateful if you can answer the other queries. If these are being obtained from somewhere else, we are better off speaking to the source. It's going to be pointless converting to uppercase if they are going to be undone by next fetch.

Also, I think we should delete the large bouquet with all channels and have 4 separate ones. Any objections?

**Comment by Lexzie** [comment]
> @Lexzie Are you downloading these lists or scanning/creating them yourself? 

It was done by scanning.
Updating was done by comparing the list on the repository with a new scan and only the differences were committed,

> Can you please check whether converting the bouquet files to upper case causes problems for your editor? https://code2care.org/2020/notepad-plus-plus-convert-text-lowercase-uppercase/

Everything in upper case is imho just as worse as everything in lower case.
Like I said, I don't know how that is happened, maybe we'd rather start with a fresh scan?


> I would be grateful if you can answer the other queries. If these are being obtained from somewhere else, we are better off speaking to the source. It's going to be pointless converting to uppercase if they are going to be undone by next fetch.

I wouldn't know.
 
> Also, I think we should delete the large bouquet with all channels and have 4 separate ones. Any objections?

No objections, please do so.

**Comment by AbuBaniaz** [comment]
>I see the 13E and 23.5E services are still in lower case.
Perhaps you don not have access to those satellites?
I can replace the services with a new scan.

I have access to 28.2, 19.2 and 13e. I am in the UK so won't have access to the European spot beam of 13e. Yes, please scan those two satellites.

**Comment by AbuBaniaz** [comment]
Also, my comments about upper/lower case were specifically with regards to service reference entries in the bouquet files. If Enigma2 writes them in capital letters, we should keep them that way. 

I don't see the point in changing the case channel names in lamedb, we should leave them as broadcast. If I changed them last time, it was a mistake, sorry.

**Comment by AbuBaniaz** [comment]
Can we please stay on this comment thread?  so all discussions/comments are in one place. Maybe we should have started an issue?

>I wanted to change the names of 11224 H and add 11344 H, but after saving a lot more was changed.
>So I discarded it. What settings editor did you use? (and what version?)

I did not use an editor. Everything was done using the receiver.

**To delete a satellite.**
Up (next to OK) > Green (satellites) > Select the satellite you want > Menu > remove selected satellite
I perform a restart to ensure nothing in RAM is used before scanning again. 

**To delete a bouquet**
Up (next to OK) > Blue (Favourites)  > Select the bouquet you want > Menu > Remove Entry
You will need to do the same for Radio channels
Best to purge delete bouquets too

**To create a bouquet**
Up (next to OK) > Green (satellites) > Select the satellite you want > Menu > Copy to Bouquet
You will need to do the same for Radio channels

**Comment by Lexzie** [comment]
> I did not use an editor. Everything was done using the receiver.


And how do you upload it to Github?
Just copy paste from /etc/eanigma2/?
I don't know for sure which files.

**Comment by AbuBaniaz** [comment]
Yes, FTP files from /etc/enigma2

`lamedb` and bouquet files.  Bouquet files are everything ending in `.tv` and `.radio`

**Comment by Lexzie** [comment]
So I have to backup the current content in /etc/enigma2/ (to place it back afterwards).
Then erase the content in /etc/enigma2/, copy the files from this repository with ftp into /etc/enigma2/.
For f.e. Astra 3B/3C to get a new clean scan, I first delete the satellite and bouquet as you stated above.
Create new bouquets with the (same) name `userbouquet.23.5E_Astra_3B3C_-_Services`, one for TV and one for radio services.
Then do a complete scan of 23.5E.

So far so good.
But how do I place all services in the bouquet with the remote control?
I only know I can do it one service at a time.

And how do I sort it alphabetically?

(I must admit I am not nearby my receiver, so I could try it first of course if there is an option to copy all services to a bouquet).

But when it is done I just have to copy just `lamedb`, `userbouquet.23.5E_Astra_3B3C_-_Services.tv` and `userbouquet.23.5E_Astra_3B3C_-_Services.radio`.

The outcome could also be different with different images, I use OpenPLi 9.

**Comment by AbuBaniaz** [comment]
You don't need to sort them alphabetically, Enigma2 will do it for you. The orbital/satellite list has always been ordered automatically.

You create the bouquets after the scan. Otherwise you are creating it with what is in lamedb (if you are following the instructions above).

**Comment by Lexzie** [comment]
> **To create a bouquet** 
Up (next to OK) > Green (satellites) > Select the satellite you want > Menu > **_Copy to Bouquet_** 
You will need to do the same for Radio channels

Indeed, reading is difficult. LOL
I will try this asap.

**Pull request merged**
